# Generated by Django 4.2.14 on 2026-09-01 09:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modules.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator')], default='operator', max_length=20)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('submit', 'Submit'), ('view', 'View'), ('upload', 'Upload'), ('login', 'Login')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('actor_ip', models.GenericIPAddressField()),
                ('actor_user_agent', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-action_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AwarenessDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_text', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('acceptance_datetime', models.DateTimeField(auto_now_add=True)),
                ('acceptance_ip', models.GenericIPAddressField()),
                ('acceptance_user_agent', models.TextField()),
                ('customer_name_declared', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-acceptance_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fiscal_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('vat_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nas_folder_name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('allowed_extensions', models.CharField(help_text='Comma-separated extensions, e.g. pdf,doc,docx', max_length=255)),
                ('mime_types', models.TextField(help_text='Comma-separated MIME types, e.g. application/pdf,application/msword')),
                ('max_file_size', models.IntegerField(help_text='Max size in bytes')),
                ('max_files', models.IntegerField(default=1)),
                ('example_file', models.FileField(blank=True, null=True, upload_to='examples/')),
                ('destination_subfolder', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('awareness_text', models.TextField(blank=True)),
                ('awareness_required_when_empty', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('form_assigned', 'Form Assigned'), ('form_submitted', 'Form Submitted'), ('document_uploaded', 'Document Uploaded'), ('form_expired', 'Form Expired')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-notification_datetime'],
                'indexes': [models.Index(fields=['status'], name='modules_not_status_be1ae7_idx'), models.Index(fields=['notification_datetime'], name='modules_not_notific_36cf6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('intro_text', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
                ('validity_end_date', models.DateTimeField(blank=True, null=True)),
                ('privacy_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.formtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secure_token', models.CharField(default=modules.models.generate_secure_token, max_length=40, unique=True)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('last_access_date', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.customer')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.formtemplate')),
                ('last_completed_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.formstep')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=500)),
                ('file_extension', models.CharField(max_length=10)),
                ('mime_type_detected', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_ip', models.GenericIPAddressField()),
                ('uploaded_by_user_agent', models.TextField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='valid', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('document_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.documentrequirement')),
                ('form_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.formassignment')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.documentupload')),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='form_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.formstep'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='modules_cus_code_f65260_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='modules_cus_email_d2d42a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['active'], name='modules_cus_active_cf7183_idx'),
        ),
        migrations.AddField(
            model_name='awarenessdeclaration',
            name='document_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.documentrequirement'),
        ),
        migrations.AddField(
            model_name='awarenessdeclaration',
            name='form_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.formassignment'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['status'], name='modules_for_status_5e6f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['created_at'], name='modules_for_created_5cca5c_idx'),
        ),
        migrations.AddIndex(
            model_name='formstep',
            index=models.Index(fields=['form_template', 'order'], name='modules_for_form_te_a6ee0b_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['secure_token'], name='modules_for_secure__5dca76_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['customer'], name='modules_for_custome_8c3ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['status'], name='modules_for_status_3ba17d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['form_assignment'], name='modules_doc_form_as_146645_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['document_requirement'], name='modules_doc_documen_379a81_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['status'], name='modules_doc_status_b92e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['form_step', 'order'], name='modules_doc_form_st_0cedd6_idx'),
        ),
        migrations.AddIndex(
            model_name='awarenessdeclaration',
            index=models.Index(fields=['form_assignment'], name='modules_awa_form_as_95e29b_idx'),
        ),
        migrations.AddIndex(
            model_name='awarenessdeclaration',
            index=models.Index(fields=['document_requirement'], name='modules_awa_documen_f545d1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user', 'action_datetime'], name='modules_aud_actor_u_1b5331_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='modules_aud_object__c961a4_idx'),
        ),
    ]
