# Generated by Django 4.2.14 on 2026-09-02 08:22

from django.db import migrations, models
import django.db.models.deletion
import modules.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('text_field', 'Text Field'), ('email_field', 'Email Field'), ('phone_field', 'Phone Field'), ('date_field', 'Date Field'), ('text_info', 'Info Text'), ('awareness_declaration', 'Awareness Declaration'), ('separator', 'Separator')], max_length=50)),
                ('order', models.IntegerField(help_text='Display order within the step')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration (label, placeholder, required, etc.)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Groups all versions of the same logical form'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nas_folder_name',
            field=models.CharField(help_text='NAS folder name (alphanumeric, hyphens, underscores only). No path traversal.', max_length=100, unique=True, validators=[modules.validators.validate_folder_name]),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='allowed_extensions',
            field=models.CharField(help_text='Comma-separated extensions, e.g. pdf,doc,docx', max_length=255, validators=[modules.validators.validate_allowed_extensions]),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='destination_subfolder',
            field=models.CharField(help_text='Subdirectory for uploads. No path traversal allowed.', max_length=255, validators=[modules.validators.validate_subfolder_name]),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='mime_types',
            field=models.TextField(help_text='Comma-separated MIME types, e.g. application/pdf,application/msword', validators=[modules.validators.validate_mime_types]),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['family_id'], name='modules_for_family__a0fd73_idx'),
        ),
        migrations.AddField(
            model_name='formelement',
            name='form_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.formstep'),
        ),
        migrations.AddIndex(
            model_name='formelement',
            index=models.Index(fields=['form_step', 'order'], name='modules_for_form_st_8a2fc0_idx'),
        ),
    ]
