# Generated by Django 4.2.14 on 2026-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_formelement_formtemplate_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formassignment',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Step 0 data: client_name, project_name, etc.'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='element_type',
            field=models.CharField(choices=[('text_field', 'Text Field'), ('email_field', 'Email Field'), ('phone_field', 'Phone Field'), ('date_field', 'Date Field'), ('text_info', 'Info Text'), ('awareness_declaration', 'Awareness Declaration'), ('separator', 'Separator'), ('client_dropdown', 'Client Selector (from NAS)'), ('project_name_field', 'Project Name Field')], max_length=50),
        ),
    ]
