# Generated by Django 4.2.14 on 2026-09-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_formassignment_form_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='allow_file_description',
            field=models.BooleanField(default=True, help_text='Allow customer to add description for each file'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='access_password',
            field=models.CharField(blank=True, help_text='Password to access this form (auto-generated if empty)', max_length=255),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Specific customer this form is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.customer'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project name for NAS folder structure', max_length=255),
        ),
    ]
