# Generated by Django 4.2.14 on 2026-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_fix_customer_empty_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_password',
            field=models.CharField(blank=True, default='', help_text='Hashed password for client portal login', max_length=128),
        ),
    ]
