# Generated by Django 4.2.14 on 2026-09-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_customer_portal_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formassignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Pratica Aperta'), ('in_progress', 'Documentazione Parziale'), ('submitted', 'Upload Documentale Completato'), ('in_processing', 'Lavorazione Etichub in Corso'), ('completed', 'Lavorazione Completata'), ('expired', 'Scaduto'), ('cancelled', 'Annullato')], default='draft', max_length=20),
        ),
    ]
