# Generated by Django 4.2.14 on 2026-09-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_alter_formassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenessdeclaration',
            name='document_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.documentrequirement'),
        ),
    ]
