# Generated by Django 4.2.14 on 2026-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_awarenessdeclaration_document_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='default_expiry_days',
            field=models.PositiveIntegerField(default=30, help_text='Default validity duration in days when assigning this form to a customer'),
        ),
    ]
