# Generated by Django 4.2.14 on 2026-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_formtemplate_default_expiry_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='max_files',
            field=models.IntegerField(default=200, help_text='Max files allowed (default 200 for batch uploads)'),
        ),
    ]
