# Generated by Django 4.2.14 on 2026-09-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_documentrequirement_max_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='max_file_size',
            field=models.IntegerField(default=10485760, help_text='Max size in bytes'),
        ),
    ]
