"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me-in-production')
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

logger = logging.getLogger('django')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'modules',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if ENVIRONMENT == 'development' and os.getenv('USE_SQLITE', 'False').lower() == 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'document_collector'),
            'USER': os.getenv('POSTGRES_USER', 'collector_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'password'),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 600,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = os.getenv('TZ', 'Europe/Rome')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# WhiteNoise: serve static files directly from Gunicorn (no Nginx needed)
import sys
if 'test' in sys.argv:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False  # Prevents 500 crashes if a static file is not in the manifest

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'data' / 'media'

# Authentication
AUTH_USER_MODEL = 'modules.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================================
# Document Management Configuration
# ==========================================================

FORM_ASSIGNMENT_EXPIRY_DAYS = 30
COMPLETION_PERCENTAGE_MULTIPLIER = 100

# ==========================================================
# CSRF, Hosts, and Security for Reverse Proxy
# ==========================================================

# Robust ALLOWED_HOSTS parsing: split, strip, discard empties
_raw_hosts = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    logger.warning('ALLOWED_HOSTS was empty after parsing, using defaults: %s', ALLOWED_HOSTS)

# Robust CSRF_TRUSTED_ORIGINS parsing:
# Robust CSRF_TRUSTED_ORIGINS parsing:
# - split by comma, strip whitespace, discard empties
# - validate each value starts with http:// or https://
# - automatically include localhost / loopback on standard dev ports
_raw_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
_csrf_set = set()

# Always trust localhost and loopback for local testing / dev
_local_hosts = ['localhost', '127.0.0.1']
_common_ports = ['', ':80', ':443', ':8000', ':6060']
_app_port = os.getenv('APP_PORT', '').strip()
if _app_port:
    _common_ports.append(f':{_app_port}')

for _h in _local_hosts:
    for _p in _common_ports:
        _csrf_set.add(f'http://{_h}{_p}')
        _csrf_set.add(f'https://{_h}{_p}')

for _origin in _raw_csrf.split(','):
    _origin = _origin.strip()
    if not _origin:
        continue
    if _origin.startswith('http://') or _origin.startswith('https://'):
        _csrf_set.add(_origin)
        # Also auto-add opposite scheme for resilience behind SSL-terminating reverse proxies
        if _origin.startswith('http://'):
            _csrf_set.add('https://' + _origin[7:])
        elif _origin.startswith('https://'):
            _csrf_set.add('http://' + _origin[8:])
    else:
        logger.warning(
            'CSRF_TRUSTED_ORIGINS: skipping malformed value "%s" '
            '(must start with http:// or https://)', _origin
        )
CSRF_TRUSTED_ORIGINS = sorted(list(_csrf_set))

# Reverse proxy support
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# SSL redirect - should be handled by reverse proxy, not Django
SECURE_SSL_REDIRECT = False

# X-Forwarded-For header for getting real client IP
X_FORWARDED_FOR_HEADER = 'HTTP_X_FORWARDED_FOR'

# Security headers
SECURE_BROWSER_XSS_FILTER = True

# Content Security Policy
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com"),
    "style-src": ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com"),
    "img-src": ("'self'", "data:", "https:"),
    "font-src": ("'self'", "https://fonts.googleapis.com", "https://fonts.gstatic.com"),
}

# Session and CSRF security
is_production = ENVIRONMENT == 'production'

# Robust ALLOWED_HOSTS parsing: split, strip, discard empties
_raw_hosts = os.getenv('ALLOWED_HOSTS', '')
_parsed_hosts = [h.strip() for h in _raw_hosts.split(',') if h.strip() and h.strip() != 'NAS_IP_HERE']

_hosts_set = set(_parsed_hosts)
# Always include loopbacks
_hosts_set.update(['localhost', '127.0.0.1'])

# Known organizational domains for EticHUB deployment (including wildcard .etichub.it)
_default_etichub_hosts = [
    'regolatorio.etichub.it',
    'service.etichub.it',
    'moduli.etichub.it',
    '.etichub.it',
    '172.17.135.184',
    '172.27.100.2',
]
# In production or if no specific hosts were configured, ensure EticHUB domains are allowed
if is_production or not _parsed_hosts:
    _hosts_set.update(_default_etichub_hosts)

# Sanitize '*' in production
if '*' in _hosts_set and is_production:
    logger.warning('SECURITY WARNING: ALLOWED_HOSTS contains "*" in production! Sanitizing.')
    _hosts_set.remove('*')

ALLOWED_HOSTS = sorted(list(_hosts_set))

# Robust CSRF_TRUSTED_ORIGINS parsing:
_raw_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
_csrf_set = set()
for origin in _raw_csrf.split(','):
    origin = origin.strip()
    if origin and (origin.startswith('http://') or origin.startswith('https://')):
        _csrf_set.add(origin)

# Always trust etichub.it domains (HTTP & HTTPS) and standard loopbacks
_csrf_set.update([
    'https://regolatorio.etichub.it',
    'http://regolatorio.etichub.it',
    'https://service.etichub.it',
    'http://service.etichub.it',
    'https://moduli.etichub.it',
    'http://moduli.etichub.it',
    'https://*.etichub.it',
    'http://*.etichub.it',
    'http://localhost:6060',
    'http://127.0.0.1:6060',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
])
CSRF_TRUSTED_ORIGINS = sorted(list(_csrf_set))

# ==========================================================
# Caches & Rate Limiting
# ==========================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ehmoduli-cache',
    }
}

import sys
_is_running_tests = 'test' in sys.argv
RATELIMIT_ENABLE = (not _is_running_tests) and (os.getenv('RATELIMIT_ENABLE', 'True' if is_production else 'False').lower() == 'true')

# ==========================================================
# Session & Cookie Security
# ==========================================================
SESSION_COOKIE_SECURE = is_production and os.getenv('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Configurable session cookie age (default: 14 days instead of 1 year)
_default_session_age = 60 * 60 * 24 * 14
try:
    SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', str(_default_session_age)))
except (ValueError, TypeError):
    SESSION_COOKIE_AGE = _default_session_age

CSRF_COOKIE_SECURE = is_production and os.getenv('CSRF_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_HTTPONLY = False  # Allows standard Django CSRF token synchronization
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'modules.views_client.csrf_failure_view'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'admin_dashboard'

# ==========================================================
# Version & Build Info
# ==========================================================
APP_VERSION = os.getenv('APP_VERSION', '2.0.1')
GIT_COMMIT = os.getenv('GIT_COMMIT', 'unknown')
BUILD_DATE = os.getenv('BUILD_DATE', 'unknown')

# Dynamic LOG_LEVEL
LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO').upper()

# Logging Configuration - writes to /app/data/django.log
# ==========================================================
LOGS_DIR = BASE_DIR / 'data' / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

_commit_short = GIT_COMMIT[:7] if GIT_COMMIT != 'unknown' else 'unknown'
_log_version_prefix = f'[v{APP_VERSION}|{_commit_short}]'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': f'[{{levelname}}] {{asctime}} {_log_version_prefix} {{name}} {{funcName}}:{{lineno}} - {{message}}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'django.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errors.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': LOG_LEVEL if LOG_LEVEL in ['DEBUG', 'INFO'] else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['file', 'error_file', 'console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'error_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'error_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file', 'error_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'INFO',  # Keep db queries to INFO unless explicitly debugging queries to avoid bloating log files
            'propagate': False,
        },
        'modules': {
            'handlers': ['file', 'error_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'accounts': {
            'handlers': ['file', 'error_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
